name: Sync Platform Branch
on:
  schedule:
    # Runs on Fridays 6:00 UTC (-6 CT, -5 EST)
    #       ┌───────────── minute (0 - 59)
    #       │ ┌───────────── hour (0 - 23)
    #       │ │ ┌───────────── day of the month (1 - 31)
    #       │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #       │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    - cron: 0 6 * * 5
    
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch: # Allow for running this manually.
          
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: Sync carbon-platform branch
          branch: carbon-platform-branch-sync
          delete-branch: true
          title: 'Sync carbon-platform branch'
          body: |
            Platform Sync, pulling in new content from main into carbon-platform branch
            ***Note***: It's ok for the CI cheks to fail on this PR, this code is not runnable due to the platform changes
          assignees: francinelucca
          reviewers: francinelucca,andreancardona,alisonjoseph
