name: Sync Platform Branch
on:
  schedule:
    # Runs on Fridays 6:00 UTC (-6 CT, -5 EST)
    #       ┌───────────── minute (0 - 59)
    #       │ ┌───────────── hour (0 - 23)
    #       │ │ ┌───────────── day of the month (1 - 31)
    #       │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #       │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    - cron: 0 6 * * 5
    
  # Enable running this workflow manually from the Actions tab
  workflow_dispatch: # Allow for running this manually.
          
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create PR branch 🤖
        run: |
          git branch carbon-platform-sync
          git push origin carbon-platform-sync
          
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            console.log(repo, owner)
            const result = await github.rest.pulls.create({
              title: 'Sync carbon-platform branch',
              owner,
              repo,
              head: 'carbon-platform-sync',
              base: 'carbon-platform',
              body: 'Platform Sync, pulling in new content from main into carbon-platform branch'
            });
            github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: result.data.number,
              reviewers: ['francinelucca', 'andreancardona', 'alisonjoseph']
            });
